# -*- coding: utf-8 -*-
"""crop_Recommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VWS2o-HDw34FkZQzHmzM9rcWaeQPuR4v
"""



import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from xgboost import XGBClassifier

"""#Random Forest Training"""

# Load dataset
data = pd.read_csv("Crop_recommendation.csv")  # change filename if needed
data.tail()

data.isnull().sum()

# Features and target
X = data.drop("label", axis=1)
y = data["label"]

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Train Random Forest
rf_model = RandomForestClassifier(
    n_estimators=200,  # number of trees
    max_depth=None,   # let it grow fully
    random_state=42
)
rf_model.fit(X_train, y_train)

# Predictions
y_pred = rf_model.predict(X_test)

# Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred)*100)
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

print("Train Accuracy:", rf_model.score(X_train, y_train))
print("Test Accuracy:", rf_model.score(X_test, y_test))

def predict_crop(N, P, K, temperature, humidity, ph, rainfall):
    input_data = [[N, P, K, temperature, humidity, ph, rainfall]]
    prediction = rf_model.predict(input_data)
    return prediction[0]

# Example
print(predict_crop(90, 429, 43, 20.8, 823, 6.5, 202))

def predict_top3_crops(model, features, label_encoder=None):
    """
    model: trained RandomForest model
    features: list/array of input features [N, P, K, temp, humidity, ph, rainfall]
    label_encoder: if labels are encoded, pass the encoder (else None)
    """
    probs = model.predict_proba([features])[0]  # get probability distribution
    top3_idx = np.argsort(probs)[-3:][::-1]     # indices of top 3 crops

    results = []
    for idx in top3_idx:
        crop = model.classes_[idx] if label_encoder is None else label_encoder.inverse_transform([idx])[0]
        results.append((crop, round(probs[idx]*100, 2)))

    return results


# Example usage
test_input = [90, 429, 43, 20.8, 823, 6.5, 202]  # replace with real input
top3 = predict_top3_crops(rf_model, test_input)

print("Top 3 Recommended Crops:")
for crop, prob in top3:
    print(f"{crop}: {prob}%")

"""#XGboost Training"""

# Encode labels
le = LabelEncoder()
y_encoded = le.fit_transform(y)

# Split dataset
X1_train, X1_test, y1_train, y1_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)

# Train XGBoost Classifier
xgb_model = XGBClassifier(
    n_estimators=300,
    learning_rate=0.1,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric="mlogloss"
)

xgb_model.fit(X1_train, y1_train)

# Predictions (numeric)
y1_pred = xgb_model.predict(X1_test)

# Accuracy
print("Accuracy:", accuracy_score(y1_test, y1_pred))

# Classification report (numeric → string labels)
print("\nClassification Report:\n", classification_report(
    le.inverse_transform(y1_test),
    le.inverse_transform(y1_pred)
))

# Confusion matrix (numeric)
print("\nConfusion Matrix:\n", confusion_matrix(y1_test, y1_pred))

print("Train Accuracy:", xgb_model.score(X1_train, y1_train))
print("Test Accuracy:", xgb_model.score(X1_test, y1_test))

def predict_top3_crops_xgb(model, features, label_encoder):
    probs = model.predict_proba([features])[0]
    top3_idx = np.argsort(probs)[-3:][::-1]

    results = []
    for idx in top3_idx:
        crop = label_encoder.inverse_transform([idx])[0]
        results.append((crop, round(probs[idx]*100, 2)))

    return results

# Example usage
test_input = [90, 429, 43, 20.8, 823, 6.5, 202]
top3 = predict_top3_crops_xgb(xgb_model, test_input, le)

print("Top 3 Recommended Crops (XGBoost):")
for crop, prob in top3:
    print(f"{crop}: {prob}%")

# Split dataset
X2_train, X2_test, y2_train, y2_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)

# Ensemble with soft voting
ensemble_model = VotingClassifier(
    estimators=[("rf", rf_model), ("xgb", xgb_model)],
    voting="soft"
)

# Train ensemble
ensemble_model.fit(X2_train, y2_train)

# Predictions
y2_pred = ensemble_model.predict(X2_test)

# Evaluation
print("Ensemble Accuracy:", accuracy_score(y2_test, y2_pred))
print("\nClassification Report:\n", classification_report(
    le.inverse_transform(y2_test),
    le.inverse_transform(y2_pred)
))
print("\nConfusion Matrix:\n", confusion_matrix(y2_test, y2_pred))

import numpy as np

def predict_top3_crops_ensemble(model, features, label_encoder):
    probs = model.predict_proba([features])[0]
    top3_idx = np.argsort(probs)[-3:][::-1]

    results = []
    for idx in top3_idx:
        crop = label_encoder.inverse_transform([idx])[0]
        results.append((crop, round(probs[idx]*100, 2)))

    return results

# Example input
test_input = [905, 429, 43, 208, 823, 6.5, 202]
top3 = predict_top3_crops_ensemble(ensemble_model, test_input, le)
print(top3)

data.tail()

# defining the inputs
N = 39
P = 42
K = 90
temperature = 2
humidity = 66.42
ph = 8.6
rainfall = 207
test_input = [N,P,K,temperature,humidity,ph,rainfall]


predictions = predict_top3_crops_ensemble(ensemble_model, test_input , le)
crops = [crop for crop, _ in predictions]
percentages = [float(score) for _, score in predictions]

print("Crops:", crops)
print("Percentages:", percentages)

from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash-preview-05-20",   # or "gemini-1.5-pro" if you want better reasoning
    google_api_key="AIzaSyAb7W_WhaHATLIL5W84ZtBW2HKkEeFslG4",
    temperature=0.3,            # adjust for more/less creativit
)

# JSON schema for crop recommendations
crop_schema = {
  "title": "CropRecommendations",
  "type": "object",
  "properties": {
    "recommendations": {
      "type": "array",
      "minItems": 3,
      "maxItems": 3,
      "items": {
        "type": "object",
        "properties": {
          "crop": { "type": "string" },
          "confidence": { "type": "number" },
          "short_description": { "type": "string" },
          "detailed_description": {
            "type": "object",
            "properties": {
              "irrigation": { "type": "string" }
            },
            "required": ["irrigation"]
          }
        },
        "required": ["crop", "confidence", "short_description", "detailed_description"]
      }
    }
  },
  "required": ["recommendations"]
}


# Attach schema (use schema= not json_schema=)
structured_llm = llm.with_structured_output(schema=crop_schema)

predictions = {
  "recommendations": [
    {"crop": crops[0], "confidence": percentages[0]},
    {"crop": crops[1], "confidence": percentages[1]},
    {"crop": crops[2], "confidence": percentages[2]}
  ]
}

prompt = f"""
You are an agricultural expert.
The ML model suggested these top crops with confidence scores:

{predictions}

For each crop, generate:
- A short description
- Detailed description including soil/fertilizer, irrigation, pests/diseases, and market insights.

Return ONLY valid JSON that follows the given schema.
"""

response = structured_llm.invoke(prompt)
print(response)

def llmcalling(N ,P ,K, temperature, humidity, ph, rainfall):
  test_input = [N,P,K,temperature,humidity,ph,rainfall]
  predictions = predict_top3_crops_ensemble(ensemble_model, test_input , le)
  crops = [crop for crop, _ in predictions]
  percentages = [float(score) for _, score in predictions]

  predictions = {
  "recommendations": [
    {"crop": crops[0], "confidence": percentages[0]},
    {"crop": crops[1], "confidence": percentages[1]},
    {"crop": crops[2], "confidence": percentages[2]}
  ]
  }
  prompt = f"""
  You are an agricultural expert.
  The ML model suggested these top crops with confidence scores:
  {predictions}
  For each crop, generate:
  - A short description
  - Detailed description including soil/fertilizer, irrigation, pests/diseases, and market insights.
  Return ONLY valid JSON that follows the given schema.
  """
  response = structured_llm.invoke(prompt)
  return response

response1 = llmcalling(12,349,435,235,354,3,3544)

response1["recommendations"]



llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash-preview-05-20",   # or "gemini-1.5-pro" if you want better reasoning
    google_api_key="AIzaSyAb7W_WhaHATLIL5W84ZtBW2HKkEeFslG4",
    temperature=0.3,            # adjust for more/less creativit
)

